### ISSUE TITLE
ebtnear.me no longer redirects to ebtnearme.org

### ISSUE THREAD

**Issue by fureigh** [codeforamerica/ebt-near-me#65]
Filing as a bug because I believe that URL's been listed publicly somewhere.

**Comment by lippytak** [comment]
Only in early conversations, I believe:
![screen shot 2015-03-21 at 1 48 24 pm](https://cloud.githubusercontent.com/assets/2533112/6766768/220b3df4-cfd1-11e4-8331-3ecc710d481b.png)

It's set not to auto-renew right now so I'd vote not to setup forwarding. Feel free to reopen if you disagree and I'll forward + start renewing it.

**Comment by fureigh** [comment]
Nah, if it's not been published on cards or used online I think it's fine to let it go. Thanks!
