### ISSUE TITLE
Get Angela more EBTNearMe data

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/ebt-near-me#66]
She wants monthly user data by county to check surcharge % change correlations (yea yea I know...questionable methodology!). This is a pretty easy lift so I'm going to do it and support her in the evaluation effort!

**Comment by daguar** [comment]
Bahhhhh teh methods tehy are so baaahd

**Comment by lippytak** [comment]
Added monthly stats by county: https://docs.google.com/spreadsheets/d/1QvuRlZ2ILqnFfVhPH0nbP8PRp8iWPZ-CNTL28n9wunc/pubhtml?gid=159972145&single=true
